### ISSUE TITLE
I cant init dark-side.

### ISSUE THREAD

**Issue by aadonald55** [naoxink/devlife#25]
When i try to init dark-side, it does not work.  Ive looked into the code and i do not understand why it does not activate.  maybe im just not seeing it?

**Comment by naoxink** [comment]
Dark-side is locked by now, it was causing much instability to the game balance :(

**Comment by aadonald55** [comment]
How is it locked?  I'm interested in how the game works and I've downloaded and modified some of the files.  I like to think I'm "learning from experience".

**Comment by aadonald55** [comment]
Thank you for replying by the way😊

**Comment by naoxink** [comment]
It's locked in the `terminal.js` at line `58`:
    return terminal.addToLog('! `dark-side` temporarily DISABLED')

Thank you for be interested in this little project ^^

**Comment by aadonald55** [comment]
Thanks.  Looking back, I dont know how i didnt think to try that.  :)

**Comment by aadonald55** [comment]
um... hate to bother you again, but i did that and nothing is happening.  Also "init dark-side" does not go away from the place where you type it in

**Comment by naoxink** [comment]
Wich browser are you using?

**Comment by aadonald55** [comment]
Im on Chrome.

**Comment by naoxink** [comment]
I found the issue: It needs `<link id="css-dark-side" rel="stylesheet" href="">` in `index.html` inside the `<head>` tag. Still doesn't change the UI color and don't know why :/

**Comment by aadonald55** [comment]
Thank you so much.  It's nice that there are nice people like you who are willing to help people like me:) thank you again
