### ISSUE TITLE
Command prompt floating numbers in ff

### ISSUE THREAD

**Issue by naoxink** [naoxink/devlife#7]
The keyup floating number (+1¢) animation in the command prompt doesn't work in Firefox.

**Comment by radumpopescu** [comment]
And in Chrome MacOS, when doing 5x for a couple of seconds, the number of floating numbers is over 9000 so the browser becomes unresponsive.

**Comment by naoxink** [comment]
@radumpopescu wich version? I don't have that issue :/

**Comment by naoxink** [comment]
Fixed here: https://github.com/naoxink/devlife/commit/db95918b0c306a662c33404150553547cf166087
